# Generated by Django 2.2 on 2020-09-26 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleHabitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('detalle', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=4, unique=True)),
                ('tipo', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('planta', models.CharField(choices=[('PB', 'Planta baja'), ('1ra', '1er Piso'), ('2da', '2do Piso'), ('3ra', '3er Piso')], max_length=3)),
                ('activa', models.BooleanField(default=True)),
                ('detalles', models.ManyToManyField(related_name='detalles_habitacion', to='reservas.DetalleHabitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('fecha_salida', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('detalle', models.TextField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_personas', models.IntegerField(default=1, help_text='Niños mayores de 12 años pagan tarifa completa')),
                ('pago_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hora_llegada', models.TimeField()),
                ('peticion_adicional', models.TextField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('PC', 'Por confirmar'), ('CF', 'Confirmada'), ('EE', 'En estadia'), ('FN', 'Finalizada'), ('CC', 'Cancelada')], default='PC', max_length=2)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.Cliente')),
                ('habitacion', models.ManyToManyField(related_name='habitaciones', to='reservas.Habitacion')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.Periodo')),
                ('servicios', models.ManyToManyField(help_text='Servicios incluidos', related_name='servicios', to='reservas.Servicio')),
            ],
        ),
    ]
