# Generated by Django 2.2 on 2020-09-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleHabitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('detalle', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='servicioincluido',
            old_name='incluye',
            new_name='activo',
        ),
        migrations.RemoveField(
            model_name='reservacion',
            name='adultos',
        ),
        migrations.RemoveField(
            model_name='reservacion',
            name='ninos',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservacion',
            name='nro_personas',
            field=models.IntegerField(default=1, help_text='Niños mayores de 12 años pagan tarifa completa'),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='pago_total',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='planta',
            field=models.CharField(choices=[('PB', 'Planta baja'), ('1ra', '1er Piso'), ('2da', '2do Piso'), ('3ra', '3er Piso')], max_length=2),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='activa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='peticion_adicional',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='servicioincluido',
            name='detalle',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='detalles',
            field=models.ManyToManyField(related_name='detalles_habitacion', to='reservas.DetalleHabitacion'),
        ),
    ]
