# Generated by Django 2.2 on 2020-09-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='foto',
            field=models.ImageField(default=None, upload_to='images/'),
            preserve_default=False,
        ),
    ]
