# Generated by Django 2.2 on 2020-09-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_auto_20200917_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='planta',
            field=models.CharField(choices=[('PB', 'Planta baja'), ('1ra', '1er Piso'), ('2da', '2do Piso'), ('3ra', '3er Piso')], max_length=3),
        ),
    ]
