# Generated by Django 2.2 on 2020-09-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_auto_20200917_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='pagada',
            field=models.BooleanField(default=False),
        ),
    ]
