# Generated by Django 2.2 on 2020-09-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_auto_20200921_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacion',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='reservacion',
            name='pagada',
        ),
        migrations.AddField(
            model_name='reservacion',
            name='estado',
            field=models.CharField(choices=[('PC', 'Por confirmar'), ('CF', 'Confirmada'), ('EE', 'En estadia'), ('FN', 'Finalizada'), ('CC', 'Cancelada')], default='PC', max_length=2),
        ),
    ]
