# Generated by Django 2.2 on 2020-09-23 04:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_auto_20200922_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='fecha_reserva',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='numero',
            field=models.CharField(max_length=4, unique=True, verbose_name='Número:'),
        ),
    ]
